title: "modifiable-risk-factors-alzheimer-latin-america"
description: "Systematic review of modifiable risk factors for Alzheimer's disease in Latin American populations (2000-2024)."
url: "https://juanmoisesd.github.io"
baseurl: "/modifiable-risk-factors-alzheimer-latin-america"
author:
  name: "Juan Moisés de la Serna Tuya"
  orcid: "0000-0002-8401-8018"
  institution: "Universidad Internacional de La Rioja (UNIR)"
plugins:
  - jekyll-seo-tag
theme: minima
